version: '2'

#volumes:
#  nextcloud:
#  db:

services:
  db:
    image: mariadb
    #restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_USER_PW=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    build: ./
    links:
      - db
    #volumes:
    #  - nextcloud:/var/www/html
    #restart: always
    ports:
      - "80:80"
      - "443:443"
